baseurl = "https://iorn.org/"
title = "Ion Orion"
defaultContentLanguage = "en"

disableHugoGeneratorInject = true
disableLiveReload = false
languageCode = "en-gb"
paginate = 4
hasCJKLanguage = true
#pygmentsUseClasses = false
#pygmentsCodefences = true
#pygmentsStyle = "pygments"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
posts = "/:year/:month/:title/"
category = "/categories/:slug/"
tag = "/tags/:slug/"

[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 3

[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/ionsqr"
weight = 1

[[menu.social]]
identifier = "mail"
name = "mail"
url = "mailto:ion@ori.onl"
weight = 2

[[menu.social]]
identifier = "link"
name = "link"
url = "https://iorn.org/"
weight = 3

[[menu.social]]
identifier = "rss"
name = "rss"
url = "https://iorn.org/index.xml"
weight = 100

[imaging]
anchor = "Smart"
bgColor = "#ffffff"
hint = "photo"
quality = 80
resampleFilter = "Lanczos"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2
style = "dracula"

[module]
 [[module.imports]]
   path = "github.com/ionsqr/simpoy"

[params]
  _merge = 'deep'