baseurl = "/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
disableLiveReload = true
languageCode = "en-gb"
title = "Simpoy"
paginate = 4
since = 2_007
hasCJKLanguage = true
pygmentsUseClasses = false
pygmentsCodefences = true
pygmentsStyle = "pygments"

[module.hugoVersion]
extended = true
min = "0.87.0"

[author]
name = "Ion Orion"

[copyright.hugo]
name = "Hugo"
url = "hahd"

[copyright.theme]
name = "Simpoy"
url = "https://github.com/ionsqr/simpoy"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true


[permalinks]
posts = "/:year/:month/:title/"
category = "/posts/categories/:slug/"
tag = "/posts/tags/:slug/"

[params]
since = 2007
quote = "Anas ibn Malik reported, The Prophet ﷺ said, <span>“Seeking knowledge is an obligation upon every Muslim.”</span> (Ibn Majah:224)"

  [params.powered]
  hugo = "Hugo"
  hugourl = "https://gohugo.io/"
  theme = "Simpoy Theme"
  themeurl = "https://github.com/ionsqr/simpoy"

  [params.license]
  name = "CC-BY-SA-4.0"
  url = "https://creativecommons.org/licenses/by-sa/4.0/"

[[menu.main]]
identifier = "category"
name = "Posts"
title = "Categories"
url = "/post/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 3

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ionsqr"
weight = 1

[[menu.social]]
identifier = "mail"
name = "Mail"
url = "mailto:ion@ori.onl"
weight = 2

[[menu.social]]
identifier = "link"
name = "link"
url = "https://iorn.org/"
weight = 3

[[menu.social]]
identifier = "rss"
name = "rss"
url = "https://simpoy.netlify.app/index.xml"
weight = 100

[imaging]
anchor = "Smart"
bgColor = "#ffffff"
hint = "photo"
quality = 80
resampleFilter = "Lanczos"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2
style = "dracula"
